services:
  app:
    image: toladev1/asset-management:latest
    container_name: asset_management_app
    restart: always
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./.env:/var/www/.env
      - asset_public:/var/www/public
    depends_on:
      - db
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: asset_management_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - asset_public:/var/www/public # Nginx needs the CSS/JS files here
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mariadb:10.6
    container_name: asset_management_db
    restart: always
    environment:
      MYSQL_DATABASE: asset_management_db
      MYSQL_USER: asset_management_user
      MYSQL_PASSWORD: asset_management_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin
    container_name: asset_management_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  dbdata:
  asset_public: # Shared volume for static assets