services:
  app:
    image: toladev1/asset-management:latest
    container_name: asset_management_app
    restart: always
    working_dir: /var/www
    env_file:
      - .env
    # REMOVE the ./:/var/www volume that is hiding your code
    volumes:
      - ./.env:/var/www/.env
      - storage_data:/var/www/storage
    depends_on:
      - db
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: asset_management_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # We use 'volumes_from' or a named volume to get the public folder
      - code_data:/var/www 
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: asset_management_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: asset_management_db
      MYSQL_USER: asset_management_user
      MYSQL_PASSWORD: asset_management_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

# ... phpmyadmin remains same ...

volumes:
  dbdata:
  storage_data:
  code_data: