
services:
  app:
    image: toladev1/asset_management_app:latest
    container_name: asset_management_app
    restart: always
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
    depends_on:
      - db
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: asset_management_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - storage_data:/var/www/storage
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: asset_management_db
    restart: always
    environment:
      MYSQL_DATABASE: asset_management_db
      MYSQL_USER: asset_management_user
      MYSQL_PASSWORD: asset_management_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  dbdata:
  storage_data:
